<?php
// Members (generated by sites/atomou/build.py from member_receiver.php.tpl; do not edit the generated file by hand).
// Login without a password: a one-time code by e-mail.  What is kept, per member, encrypted at rest (AES-256-GCM, key file outside the
// web root): the e-mail address, the plan / first-come tier and its end date, the referral code, the sessions (hashes), and — only when
// the member switched it on — the days to notify by e-mail with a short title each.  Nothing else.  Files: <site folder>/members/ (outside
// public_html): key (32 random bytes), counter.json (first-come numbers), pending/<id>.json (codes, 10 minutes), m/<id>.json (members).
// Every answer is JSON.  Every request is a POST with a JSON body {"v":1,"a":"<action>", ...}.  Actions: code, verify, seats, thanks, me, update, survey, logout, delete.
date_default_timezone_set('Asia/Tokyo');
header('Content-Type: application/json; charset=utf-8');
header('Cache-Control: no-store');
header('X-Robots-Tag: noindex');
$TIERS = __TIERS__;             // first-come tiers in order: [{"id":"tester","size":100,"months":18}, ...]  (from config.json; the owner decides the numbers)
$REF_MONTHS = __REF_MONTHS__;   // months a referred member gets after the tiers are full
$REF_GIVE = __REF_GIVE__;       // months the referrer gets per referral (single level, capped)
$REF_CAP = __REF_CAP__;         // the most referrals a member is rewarded for
$MAIL_FROM = '__MAIL_FROM__';   // the sender of the code mails (owner: a mailbox of the domain with SPF/DKIM)
$SITE_NAME = '__SITE_NAME__';
$SITE_URL = '__SITE_URL__';

$IDS = array_map(function ($t) { return $t['id']; }, $TIERS);

function out($code, $data) { http_response_code($code); echo json_encode($data, JSON_UNESCAPED_UNICODE); exit; }
if (($_SERVER['REQUEST_METHOD'] ?? '') !== 'POST') { out(405, array('error' => 'method')); }
$origin = (string)($_SERVER['HTTP_ORIGIN'] ?? '');
if ($origin !== '' && $origin !== $SITE_URL) { out(403, array('error' => 'origin')); }   // the pages of this site only (CSRF)
$raw = file_get_contents('php://input', false, null, 0, 65537);
if ($raw === false || strlen($raw) > 65536) { out(413, array('error' => 'size')); }
$d = json_decode($raw, true);
if (!is_array($d) || ($d['v'] ?? 0) !== 1 || !is_string($d['a'] ?? null)) { out(400, array('error' => 'request')); }
$site = dirname(__DIR__, 2);
$root = $site . '/members';
foreach (array($root, $root . '/pending', $root . '/m') as $dir) { if (!is_dir($dir) && !@mkdir($dir, 0700, true)) { out(503, array('error' => 'storage')); } }

// ---------- rate limit per sender and day (same scheme as the other receivers) ----------
$ip = (string)($_SERVER['REMOTE_ADDR'] ?? '');
$who = substr(hash('sha256', $ip . '|' . date('Y-m-d') . '|' . basename($site) . '|members'), 0, 16);
$rate = $root . '/rate-' . date('Ymd') . '-' . $who;
$r = is_file($rate) ? (int)file_get_contents($rate) : 0;
if ($r >= 200) { out(429, array('error' => 'rate')); }
@file_put_contents($rate, (string)($r + 1), LOCK_EX);
foreach ((glob($root . '/rate-*') ?: array()) as $f) { if (strpos($f, '/rate-' . date('Ymd') . '-') === false) { @unlink($f); } }

// ---------- encryption at rest ----------
function master_key($root) {
    $f = $root . '/key';
    if (!is_file($f)) { $k = random_bytes(32); if (@file_put_contents($f, $k, LOCK_EX) === false) { out(503, array('error' => 'key')); } @chmod($f, 0600); }
    $k = (string)file_get_contents($f);
    if (strlen($k) !== 32) { out(503, array('error' => 'key')); }
    return $k;
}
function seal($root, $arr) {
    $iv = random_bytes(12); $tag = '';
    $c = openssl_encrypt(json_encode($arr, JSON_UNESCAPED_UNICODE), 'aes-256-gcm', master_key($root), OPENSSL_RAW_DATA, $iv, $tag);
    if ($c === false) { out(503, array('error' => 'seal')); }
    return base64_encode($iv . $tag . $c);
}
function unseal($root, $b64) {
    $bin = base64_decode((string)$b64, true);
    if ($bin === false || strlen($bin) < 29) { return null; }
    $p = openssl_decrypt(substr($bin, 28), 'aes-256-gcm', master_key($root), OPENSSL_RAW_DATA, substr($bin, 0, 12), substr($bin, 12, 16));
    $a = $p === false ? null : json_decode($p, true);
    return is_array($a) ? $a : null;
}
function member_id($email) { return hash('sha256', 'member|' . $email); }
function load_member($root, $id) {
    $f = $root . '/m/' . $id . '.json';
    if (!is_file($f)) { return null; }
    return unseal($root, (string)file_get_contents($f));
}
function save_member($root, $id, $m) {
    $f = $root . '/m/' . $id . '.json'; $tmp = $f . '.tmp';
    if (@file_put_contents($tmp, seal($root, $m), LOCK_EX) === false || !@rename($tmp, $f)) { @unlink($tmp); out(503, array('error' => 'save')); }
    @chmod($f, 0600);
}
function public_view($m) {   // what the browser gets: never the sessions, never other members' data
    return array('email' => $m['email'], 'plan' => $m['plan'], 'tier' => $m['tier'], 'free_until' => $m['free_until'], 'ref_code' => $m['ref_code'],
                 'referrals' => (int)($m['referrals'] ?? 0), 'notices' => array('on' => !empty($m['notices']['on']), 'weekly' => !empty($m['notices']['weekly']), 'n' => count($m['notices']['dates'] ?? array())), 'created' => $m['created'],
                 'surveys' => array_map('intval', array_keys(is_array($m['survey'] ?? null) ? $m['survey'] : array())),
                 'pen' => (string)($m['pen'] ?? ''), 'pen_ok' => !empty($m['pen_ok']), 'badges' => badges_of($m));
}
function badges_of($m) {   // shown on the my page; 'early' comes from the first-come places, the others from the monthly awards
    $b = in_array($m['tier'] ?? '', array('tester', 'first'), true) ? array('early') : array();
    foreach ((is_array($m['badges'] ?? null) ? $m['badges'] : array()) as $x) { if (!in_array($x, $b, true)) { $b[] = $x; } }
    return $b;
}
function extend($m, $months, $today) {
    $base = (($m['free_until'] ?? '') !== '' && $m['free_until'] > $today) ? $m['free_until'] : $today;
    $m['free_until'] = months_later($base, $months);
    return $m;
}
function months_later($iso, $months) { $t = new DateTime($iso); $t->modify('+' . (int)$months . ' months'); return $t->format('Y-m-d'); }
function find_by_ref($root, $code) {   // the referral code is short; the members folder is small enough to scan (hundreds to thousands)
    foreach ((glob($root . '/m/*.json') ?: array()) as $f) { $m = unseal($root, (string)file_get_contents($f)); if ($m && ($m['ref_code'] ?? '') === $code) { return array(basename($f, '.json'), $m); } }
    return null;
}

// ---------- session ----------
function session_member($root) {
    $tok = (string)($_COOKIE['atomou_s'] ?? '');
    if (!preg_match('/^[a-f0-9]{64}\.[A-Za-z0-9_-]{43}$/', $tok)) { return null; }
    list($id, $secret) = explode('.', $tok, 2);
    $m = load_member($root, $id);
    if (!$m) { return null; }
    $h = hash('sha256', $secret); $now = time(); $keep = array(); $ok = false;
    foreach (($m['sessions'] ?? array()) as $s) { if (($s['exp'] ?? 0) > $now) { $keep[] = $s; if (hash_equals($s['h'], $h)) { $ok = true; } } }
    if (count($keep) !== count($m['sessions'] ?? array())) { $m['sessions'] = $keep; save_member($root, $id, $m); }
    return $ok ? array($id, $m) : null;
}
function set_cookie($value, $exp) {
    $secure = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off');
    setcookie('atomou_s', $value, array('expires' => $exp, 'path' => '/api/', 'secure' => $secure, 'httponly' => true, 'samesite' => 'Lax'));
}

$a = $d['a'];
$email = strtolower(trim((string)($d['email'] ?? '')));
$valid_email = $email !== '' && strlen($email) <= 254 && filter_var($email, FILTER_VALIDATE_EMAIL) !== false && !preg_match('/[\r\n]/', $email);

if ($a === 'code') {
    // Always 204: whether the address is known or not is not revealed.  Per address: 3 codes an hour.
    if (!$valid_email) { out(204, array()); }
    $id = member_id($email);
    $pf = $root . '/pending/' . $id . '.json';
    $p = is_file($pf) ? json_decode((string)file_get_contents($pf), true) : null;
    $sent = is_array($p) && is_array($p['sent'] ?? null) ? array_values(array_filter($p['sent'], function ($t) { return $t > time() - 3600; })) : array();
    if (count($sent) >= 3) { out(204, array()); }
    $code = str_pad((string)random_int(0, 999999), 6, '0', STR_PAD_LEFT);
    $sent[] = time();
    $rec = array('h' => password_hash($code, PASSWORD_DEFAULT), 'exp' => time() + 600, 'tries' => 0, 'sent' => $sent, 'ref' => preg_match('/^[A-Z2-9]{8}$/', (string)($d['ref'] ?? '')) ? $d['ref'] : '', 'want' => in_array((string)($d['want'] ?? ''), $IDS, true) ? (string)$d['want'] : '');
    @file_put_contents($pf, json_encode($rec), LOCK_EX); @chmod($pf, 0600);
    $subject = '【' . $SITE_NAME . '】ログインの確認コード: ' . $code;
    $body = "確認コード: " . $code . "\n\n10分以内に、画面に入力してください。\nこのメールに心当たりがない場合は、何もしなくて大丈夫です。\n\n" . $SITE_NAME . "\n" . $SITE_URL . "\n";
    $headers = 'From: ' . $SITE_NAME . ' <' . $MAIL_FROM . '>' . "\r\n" . 'Content-Type: text/plain; charset=UTF-8' . "\r\n" . 'Content-Transfer-Encoding: 8bit';
    @mail($email, '=?UTF-8?B?' . base64_encode($subject) . '?=', $body, $headers, '-f ' . $MAIL_FROM);
    out(204, array());
}

if ($a === 'verify') {
    $code = preg_replace('/\D/', '', (string)($d['code'] ?? ''));
    if (!$valid_email || strlen($code) !== 6) { out(400, array('error' => 'code')); }
    $id = member_id($email);
    $pf = $root . '/pending/' . $id . '.json';
    $p = is_file($pf) ? json_decode((string)file_get_contents($pf), true) : null;
    if (!is_array($p) || ($p['exp'] ?? 0) < time() || ($p['tries'] ?? 0) >= 5) { @unlink($pf); out(400, array('error' => 'expired')); }
    if (!password_verify($code, $p['h'])) { $p['tries'] = ($p['tries'] ?? 0) + 1; @file_put_contents($pf, json_encode($p), LOCK_EX); out(400, array('error' => 'wrong', 'left' => 5 - $p['tries'])); }
    @unlink($pf);
    $m = load_member($root, $id);
    $today = date('Y-m-d');
    if (!$m) {
        // a new member: each first-come pool (the tester places and the ordinary places) counts on its own, offered at the same time; the
        // visitor chose one.  A full tester pool falls back to the ordinary places (never the other way: testers have a condition).
        // The referral code (if any) is honoured when there is no room.
        $cf = $root . '/counter.json';
        $fh = @fopen($cf, 'c+'); if (!$fh) { out(503, array('error' => 'counter')); }
        flock($fh, LOCK_EX);
        $c = json_decode((string)stream_get_contents($fh), true); if (!is_array($c)) { $c = array(); }
        if (!is_array($c['by'] ?? null)) { $c['by'] = array(); }
        $n = (int)($c['n'] ?? 0) + 1; $c['n'] = $n;
        $tier = ''; $months = 0; $want = (string)($p['want'] ?? ''); $order = array();
        foreach ($TIERS as $t) { if ($t['id'] === $want) { array_unshift($order, $t); } elseif (empty($t['tester'])) { $order[] = $t; } }
        foreach ($order as $t) { $used = (int)($c['by'][$t['id']] ?? 0); if ($used < (int)$t['size']) { $c['by'][$t['id']] = $used + 1; $tier = $t['id']; $months = (int)$t['months']; break; } }
        ftruncate($fh, 0); rewind($fh); fwrite($fh, json_encode($c)); fflush($fh); flock($fh, LOCK_UN); fclose($fh);
        $ref_by = '';
        if ($tier === '' && $p['ref'] !== '') { $found = find_by_ref($root, $p['ref']); if ($found && $found[0] !== $id) { $tier = 'referred'; $months = $REF_MONTHS; $ref_by = $found[0]; } }
        do { $code_new = ''; for ($i = 0; $i < 8; $i++) { $code_new .= substr('ABCDEFGHJKLMNPQRSTUVWXYZ23456789', random_int(0, 31), 1); } } while (find_by_ref($root, $code_new));
        $m = array('email' => $email, 'created' => $today, 'number' => $n, 'plan' => 'free', 'tier' => $tier, 'free_until' => $months ? months_later($today, $months) : '',
                   'ref_code' => $code_new, 'ref_by' => $ref_by, 'referrals' => 0, 'sessions' => array(), 'notices' => array('on' => false, 'dates' => array()));
        // the referrer is rewarded later, when this person has used the site on two days at least a week apart (the visit block after the login check):
        // a throwaway address registered only for the reward never counts
    }
    $secret = rtrim(strtr(base64_encode(random_bytes(32)), '+/', '-_'), '=');
    $exp = time() + 90 * 86400;
    $m['seen'] = array_slice(array_values(array_unique(array_merge(is_array($m['seen'] ?? null) ? $m['seen'] : array(), array($today)))), -20);
    $m['sessions'][] = array('h' => hash('sha256', $secret), 'exp' => $exp, 'made' => $today);
    if (count($m['sessions']) > 10) { $m['sessions'] = array_slice($m['sessions'], -10); }
    save_member($root, $id, $m);
    set_cookie($id . '.' . $secret, $exp);
    out(200, array('member' => public_view($m)));
}

if ($a === 'seats') {   // public: the places left in each first-come pool (no personal data)
    $c = is_file($root . '/counter.json') ? json_decode((string)file_get_contents($root . '/counter.json'), true) : null;
    $by = is_array($c) && is_array($c['by'] ?? null) ? $c['by'] : array(); $pools = array();
    foreach ($TIERS as $t) { $pools[] = array('id' => $t['id'], 'left' => max(0, (int)$t['size'] - (int)($by[$t['id']] ?? 0)), 'size' => (int)$t['size'], 'months' => (int)$t['months'], 'tester' => !empty($t['tester'])); }
    out(200, array('pools' => $pools, 'ref_months' => $REF_MONTHS));
}

if ($a === 'thanks') {   // public: written by the monthly job (sites/atomou/monthly.py); only consented pen names, never an address
    $t = is_file($root . '/thanks.json') ? json_decode((string)file_get_contents($root . '/thanks.json'), true) : null;
    out(200, is_array($t) ? $t : array('months' => array()));
}

$s = session_member($root);
if (!$s) { out(401, array('error' => 'login')); }
list($id, $m) = $s;

// ---------- on every visit of a member: the day of use, the referral check, the monthly awards ----------
$today = date('Y-m-d'); $changed = false;
$seen = is_array($m['seen'] ?? null) ? $m['seen'] : array();
if (!in_array($today, $seen, true)) { $seen[] = $today; $m['seen'] = array_slice($seen, -20); $changed = true; }
if (($m['ref_by'] ?? '') !== '' && empty($m['ref_ok']) && count($m['seen']) >= 2 && strtotime(max($m['seen'])) - strtotime(min($m['seen'])) >= 7 * 86400) {
    $m['ref_ok'] = $today; $changed = true;
    $rm = load_member($root, $m['ref_by']);
    if ($rm && (int)($rm['referrals'] ?? 0) < $REF_CAP) {   // single level, time only, capped
        $rm['referrals'] = (int)($rm['referrals'] ?? 0) + 1;
        $rm = extend($rm, $REF_GIVE, $today);
        $rm['ref_log'] = array_slice(array_merge(is_array($rm['ref_log'] ?? null) ? $rm['ref_log'] : array(), array(date('Y-m'))), -60);
        save_member($root, $m['ref_by'], $rm);
    }
}
$aw = is_file($root . '/awards.json') ? json_decode((string)file_get_contents($root . '/awards.json'), true) : null;
if (is_array($aw) && is_array($aw[$id] ?? null)) {   // written by the monthly job; each award is applied once (by its key)
    $done = is_array($m['awards_done'] ?? null) ? $m['awards_done'] : array();
    foreach ($aw[$id] as $x) {
        $key = (string)($x['key'] ?? '');
        if ($key === '' || in_array($key, $done, true)) { continue; }
        if ((int)($x['months'] ?? 0) > 0) { $m = extend($m, min(12, (int)$x['months']), $today); }
        $badge = (string)($x['badge'] ?? '');
        if (preg_match('/^[a-z_]{1,20}$/', $badge)) { $b = is_array($m['badges'] ?? null) ? $m['badges'] : array(); if (!in_array($badge, $b, true)) { $b[] = $badge; } $m['badges'] = $b; }
        $done[] = $key; $changed = true;
    }
    $m['awards_done'] = array_slice($done, -100);
}
if ($changed) { save_member($root, $id, $m); }

if ($a === 'me') { out(200, array('member' => public_view($m))); }

if ($a === 'update') {
    // the e-mail notices: on/off and the days (date, slot, a short title); only here does a title reach the server, and only with this switch on
    if (is_array($d['notices'] ?? null)) {
        $on = !empty($d['notices']['on']); $dates = array(); $n = 0;
        foreach ((is_array($d['notices']['dates'] ?? null) ? $d['notices']['dates'] : array()) as $x) {
            if (++$n > 400) { break; }
            if (!is_array($x) || !is_string($x['d'] ?? null) || !preg_match('/^\d{4}-\d{2}-\d{2}$/', $x['d'])) { continue; }
            $dates[] = array('d' => $x['d'], 's' => ($x['s'] ?? 'm') === 'e' ? 'e' : 'm', 't' => mb_substr((string)($x['t'] ?? ''), 0, 60));
        }
        $weekly = $on && !empty($d['notices']['weekly']);   // the Monday digest: only for a member who also has the notices on (the days it lists are those notices)
        $m['notices'] = array('on' => $on, 'weekly' => $weekly, 'dates' => $on ? $dates : array(), 'updated' => date('c'));
    }
    if (array_key_exists('pen', $d)) {   // the name on the thanks page: 20 characters, no address, no link, no phone number
        $pen = mb_substr(trim(preg_replace('/[\x00-\x1F\x7F<>"\'&]/u', '', (string)$d['pen'])), 0, 20);
        if (preg_match('/@|https?:|www\.|\d{7,}/i', $pen)) { out(400, array('error' => 'pen')); }
        $m['pen'] = $pen;
    }
    if (array_key_exists('pen_ok', $d)) { $m['pen_ok'] = !empty($d['pen_ok']) && ($m['pen'] ?? '') !== ''; }
    save_member($root, $id, $m);
    out(200, array('member' => public_view($m)));
}

if ($a === 'survey') {   // the monitor's one-minute questionnaire (tier id 'tester'): n = 1 (after a week) or 2 (after a month); two fixed choices and one short free text
    if (($m['tier'] ?? '') !== 'tester') { out(403, array('error' => 'tester')); }
    $n = (int)($d['n'] ?? 0);
    if ($n !== 1 && $n !== 2) { out(400, array('error' => 'survey')); }
    $ans = is_array($d['answers'] ?? null) ? $d['answers'] : array();
    $freq = in_array((string)($ans['freq'] ?? ''), array('daily', 'weekly', 'rarely'), true) ? (string)$ans['freq'] : '';
    $use = in_array((string)($ans['use'] ?? ''), array('count', 'calendar', 'todo', 'official', 'notice', 'other'), true) ? (string)$ans['use'] : '';
    if ($freq === '' || $use === '') { out(400, array('error' => 'answers')); }
    if (!is_array($m['survey'] ?? null)) { $m['survey'] = array(); }
    $m['survey'][(string)$n] = array('at' => date('Y-m-d'), 'freq' => $freq, 'use' => $use, 'text' => mb_substr(trim((string)($ans['text'] ?? '')), 0, 300));
    save_member($root, $id, $m);
    out(200, array('member' => public_view($m)));
}

if ($a === 'logout') {
    $tok = (string)($_COOKIE['atomou_s'] ?? ''); $secret = substr($tok, 65); $h = hash('sha256', $secret);
    $m['sessions'] = array_values(array_filter($m['sessions'], function ($x) use ($h) { return !hash_equals($x['h'], $h); }));
    save_member($root, $id, $m);
    set_cookie('', time() - 3600);
    out(200, array('ok' => true));
}

if ($a === 'delete') {   // the right to be forgotten: the record goes at once; the referral counter of the referrer is not touched
    @unlink($root . '/m/' . $id . '.json');
    set_cookie('', time() - 3600);
    out(200, array('ok' => true));
}

out(400, array('error' => 'action'));
