<?php
// Receiver of the push subscriptions (generated by sites/atomou/build.py from push_receiver.php.tpl; do not edit the generated file by hand).
// Stored per subscription, in <site folder>/push/ (outside the web root): the endpoint, the two keys the browser made, and the days on
// which to knock ("dates": [{"d": "2026-10-20", "s": "m"}]).  No titles, no names, no address.  The sender (a GitHub workflow) reads this
// folder over SSH twice a day and sends one content-free message per due subscription; the device composes the text itself.
date_default_timezone_set('Asia/Tokyo');
header('X-Robots-Tag: noindex');
header('Cache-Control: no-store');
if (($_SERVER['REQUEST_METHOD'] ?? '') !== 'POST') { http_response_code(405); exit; }
$origin = (string)($_SERVER['HTTP_ORIGIN'] ?? '');
if ($origin !== '' && $origin !== '__SITE_URL__') { http_response_code(403); exit; }   // the pages of this site only
$raw = file_get_contents('php://input', false, null, 0, 16385);
if ($raw === false || strlen($raw) > 16384) { http_response_code(413); exit; }
$d = json_decode($raw, true);
if (!is_array($d) || ($d['v'] ?? 0) !== 1) { http_response_code(400); exit; }
$site = dirname(__DIR__, 2);                       // public_html/api/push.php -> <site folder>
$dir = $site . '/push';
if (!is_dir($dir) && !@mkdir($dir, 0700, true)) { http_response_code(503); exit; }
// A limit on requests per sender and day (same scheme as the statistics receiver): a salted daily hash of the address in a counter file removed the next day.
$ip = (string)($_SERVER['REMOTE_ADDR'] ?? '');
$who = substr(hash('sha256', $ip . '|' . date('Y-m-d') . '|' . basename($site) . '|push'), 0, 16);
$rate = $dir . '/rate-' . date('Ymd') . '-' . $who;
$r = is_file($rate) ? (int)file_get_contents($rate) : 0;
if ($r >= 120) { http_response_code(429); exit; }
@file_put_contents($rate, (string)($r + 1), LOCK_EX);
foreach ((glob($dir . '/rate-*') ?: array()) as $f) { if (strpos($f, '/rate-' . date('Ymd') . '-') === false) { @unlink($f); } }

$endpoint = $d['endpoint'] ?? (is_array($d['sub'] ?? null) ? ($d['sub']['endpoint'] ?? '') : '');
if (!is_string($endpoint) || strlen($endpoint) > 1024 || !preg_match('#^https://[A-Za-z0-9.-]+(:\d+)?/[^\s"<>]*$#', $endpoint)) { http_response_code(400); exit; }
// Only the push services of the browsers (Chrome/Android, Firefox, Safari/iOS, Edge): the sender would otherwise POST to any address a visitor names.
if (!preg_match('#^https://([A-Za-z0-9-]+\.)*(googleapis\.com|push\.services\.mozilla\.com|mozaws\.net|push\.apple\.com|notify\.windows\.com)(:\d+)?/#', $endpoint)) { http_response_code(400); exit; }
$file = $dir . '/' . hash('sha256', $endpoint) . '.json';

if (!empty($d['off'])) {                           // the visitor switched the notifications off: forget the subscription at once
    @unlink($file);
    http_response_code(204); exit;
}
$keys = is_array($d['sub'] ?? null) && is_array($d['sub']['keys'] ?? null) ? $d['sub']['keys'] : null;
$b64 = '#^[A-Za-z0-9_-]{10,200}$#';
if (!$keys || !is_string($keys['p256dh'] ?? null) || !is_string($keys['auth'] ?? null) || !preg_match($b64, $keys['p256dh']) || !preg_match($b64, $keys['auth'])) { http_response_code(400); exit; }
$dates = array(); $n = 0;
foreach ((is_array($d['dates'] ?? null) ? $d['dates'] : array()) as $x) {
    if (++$n > 400) { break; }
    if (!is_array($x) || !is_string($x['d'] ?? null) || !preg_match('/^\d{4}-\d{2}-\d{2}$/', $x['d'])) { continue; }
    $s = ($x['s'] ?? 'm') === 'e' ? 'e' : 'm';
    $dates[$x['d'] . $s] = array('d' => $x['d'], 's' => $s);
}
// Shared cards the visitor asked to hear about (a separate opt-in on the my page): the card's id and the version this device has seen.  'sent' is the newest version already announced
// to this subscription, kept across re-registrations so that the same change is never announced twice.
$watch = array(); $nw = 0;
foreach ((is_array($d['watch'] ?? null) ? $d['watch'] : array()) as $x) {
    if (++$nw > 30) { break; }
    if (!is_array($x) || !is_string($x['id'] ?? null) || !preg_match('/^[A-Za-z0-9_-]{22}$/', $x['id'])) { continue; }
    $watch[$x['id']] = array('id' => $x['id'], 'ver' => max(0, min(1000000, (int)($x['ver'] ?? 0))), 'sent' => 0);
}
if ($watch && is_file($file)) {
    $old = json_decode((string)@file_get_contents($file), true);
    foreach ((is_array($old) && is_array($old['watch'] ?? null)) ? $old['watch'] : array() as $o) {
        if (is_array($o) && is_string($o['id'] ?? null) && isset($watch[$o['id']])) { $watch[$o['id']]['sent'] = max($watch[$o['id']]['sent'], (int)($o['sent'] ?? 0)); }
    }
}
$rec = array('endpoint' => $endpoint, 'keys' => array('p256dh' => $keys['p256dh'], 'auth' => $keys['auth']), 'dates' => array_values($dates), 'watch' => array_values($watch), 'updated' => date('c'));
$tmp = $file . '.tmp';
if (@file_put_contents($tmp, json_encode($rec), LOCK_EX) === false || !@rename($tmp, $file)) { @unlink($tmp); http_response_code(503); exit; }
@chmod($file, 0600);
http_response_code(204);
