<?php
// Shared cards that stay up to date (generated by sites/atomou/build.py from share_receiver.php.tpl; do not edit the generated file by hand).
// What the server holds of a card: an id (random, made by the browser), the CIPHERTEXT of the card (AES-GCM, the key is in the part of the link after "#" and never reaches the server),
// a version number, three times, the SHA-256 of the edit token (the token itself stays in the editors' links), a list of hashed reporters and a "blocked" flag.  It cannot read a card.
// Files: <site folder>/shared/c-<id>.json (outside public_html).  Every answer is JSON.  Every request is a POST with a JSON body {"v":1,"a":"<action>", ...}.
// Actions: peek {items:[{id,ver}]}, get {id, ver?}, create {id, eh, ct}, update {id, e, base, ct}, delete {id, e}, report {id}.
date_default_timezone_set('Asia/Tokyo');
header('Content-Type: application/json; charset=utf-8');
header('Cache-Control: no-store');
header('X-Robots-Tag: noindex');
$SITE_URL = '__SITE_URL__';
$MAX_CT = 8192;            // the longest ciphertext (characters, base64url)
$KEEP_DAYS = 180;          // a card nobody changed for this long is deleted
$MAX_FILES = 20000;        // the most cards the server keeps
$CREATE_PER_DAY = 20;      // per sender and day
$BLOCK_AT = 3;             // reporters that stop a card

function out($code, $data) { http_response_code($code); echo json_encode($data, JSON_UNESCAPED_UNICODE); exit; }
if (($_SERVER['REQUEST_METHOD'] ?? '') !== 'POST') { out(405, array('error' => 'method')); }
$origin = (string)($_SERVER['HTTP_ORIGIN'] ?? '');
$oh = (string)parse_url($origin, PHP_URL_HOST); $sh = (string)parse_url($SITE_URL, PHP_URL_HOST);
if ($origin !== '' && $oh !== $sh && substr($oh, -(strlen($sh) + 1)) !== '.' . $sh) { out(403, array('error' => 'origin')); }   // the pages of this site (and its demo sub-domain) only
$raw = file_get_contents('php://input', false, null, 0, 20001);
if ($raw === false || strlen($raw) > 20000) { out(413, array('error' => 'size')); }
$d = json_decode($raw, true);
if (!is_array($d) || ($d['v'] ?? 0) !== 1 || !is_string($d['a'] ?? null)) { out(400, array('error' => 'request')); }
$site = dirname(__DIR__, 2);                       // public_html/api/s.php -> <site folder>   (public_html/demo/api/s.php -> the same one)
$root = $site . '/shared';
if (!is_dir($root) && !@mkdir($root, 0700, true)) { out(503, array('error' => 'storage')); }

$ip = (string)($_SERVER['REMOTE_ADDR'] ?? '');
$who = substr(hash('sha256', $ip . '|' . date('Y-m-d') . '|' . basename($site) . '|shared'), 0, 16);   // a salted daily hash: not an address, not kept after the day
$rate = $root . '/rate-' . date('Ymd') . '-' . $who;
$r = is_file($rate) ? (int)file_get_contents($rate) : 0;
if ($r >= 600) { out(429, array('error' => 'rate')); }
@file_put_contents($rate, (string)($r + 1), LOCK_EX);
foreach ((glob($root . '/rate-*') ?: array()) as $f) { if (strpos($f, '/rate-' . date('Ymd') . '-') === false) { @unlink($f); } }
$made = $root . '/made-' . date('Ymd') . '-' . $who;

function valid_id($s) { return is_string($s) && preg_match('/^[A-Za-z0-9_-]{22}$/', $s) === 1; }
function valid_b64($s, $max) { return is_string($s) && $s !== '' && strlen($s) <= $max && preg_match('/^[A-Za-z0-9_-]+$/', $s) === 1; }
function path_of($root, $id) { return $root . '/c-' . $id . '.json'; }
function read_card($path) { if (!is_file($path)) { return null; } $c = json_decode((string)file_get_contents($path), true); return is_array($c) ? $c : null; }
function write_card($path, $c) { $ok = @file_put_contents($path, json_encode($c), LOCK_EX) !== false; if ($ok) { @chmod($path, 0600); } return $ok; }
function editor_ok($c, $e) { return is_string($e) && preg_match('/^[A-Za-z0-9_-]{20,64}$/', $e) === 1 && hash_equals((string)$c['eh'], hash('sha256', $e)); }

$a = $d['a'];
if ($a === 'peek') {   // which of the cards I follow have a newer version?  One request for up to 20 cards: [{"id":..., "ver":...}]
    $items = is_array($d['items'] ?? null) ? array_slice($d['items'], 0, 20) : array();
    $changed = array();
    foreach ($items as $it) {
        if (!is_array($it) || !valid_id($it['id'] ?? '')) { continue; }
        $c = read_card(path_of($root, $it['id']));
        if ($c === null || !empty($c['blocked']) || (int)$c['exp'] < time()) { $changed[] = array('id' => $it['id'], 'gone' => true); continue; }
        if ((int)($it['ver'] ?? 0) !== (int)$c['ver']) { $changed[] = array('id' => $it['id'], 'ver' => (int)$c['ver'], 'upd' => (int)$c['upd']); }
    }
    out(200, array('ok' => true, 'changed' => $changed));
}
$id = $d['id'] ?? '';
if (!valid_id($id)) { out(400, array('error' => 'id')); }
$path = path_of($root, $id);
$now = time();

if ($a === 'get') {
    $c = read_card($path);
    if ($c === null) { out(404, array('error' => 'none')); }
    if (!empty($c['blocked'])) { out(410, array('error' => 'blocked')); }
    if ((int)$c['exp'] < $now) { @unlink($path); out(404, array('error' => 'none')); }
    if (isset($d['ver']) && (int)$d['ver'] === (int)$c['ver']) { out(200, array('ok' => true, 'same' => true, 'ver' => (int)$c['ver'])); }
    out(200, array('ok' => true, 'ver' => (int)$c['ver'], 'ct' => $c['ct'], 'upd' => (int)$c['upd']));
}

if ($a === 'create') {
    if (!valid_b64($d['ct'] ?? null, $MAX_CT) || !is_string($d['eh'] ?? null) || preg_match('/^[0-9a-f]{64}$/', $d['eh']) !== 1) { out(400, array('error' => 'card')); }
    $n = is_file($made) ? (int)file_get_contents($made) : 0;
    if ($n >= $CREATE_PER_DAY) { out(429, array('error' => 'limit')); }
    $files = glob($root . '/c-*.json') ?: array();
    if (count($files) >= $MAX_FILES) {   // make room: the cards past their time go first
        foreach ($files as $f) { $c = read_card($f); if ($c === null || (int)$c['exp'] < $now) { @unlink($f); } }
        if (count(glob($root . '/c-*.json') ?: array()) >= $MAX_FILES) { out(503, array('error' => 'full')); }
    }
    if (is_file($path)) { out(409, array('error' => 'exists')); }
    $c = array('eh' => $d['eh'], 'ct' => $d['ct'], 'ver' => 1, 'created' => $now, 'upd' => $now, 'exp' => $now + $KEEP_DAYS * 86400, 'rep' => array(), 'blocked' => false);
    if (!write_card($path, $c)) { out(503, array('error' => 'write')); }
    @file_put_contents($made, (string)($n + 1), LOCK_EX);
    foreach ((glob($root . '/made-*') ?: array()) as $f) { if (strpos($f, '/made-' . date('Ymd') . '-') === false) { @unlink($f); } }
    out(200, array('ok' => true, 'ver' => 1, 'upd' => $now));
}

$c = read_card($path);
if ($c === null) { out(404, array('error' => 'none')); }

if ($a === 'report') {
    $reps = is_array($c['rep'] ?? null) ? $c['rep'] : array();
    if (!in_array($who, $reps, true)) { $reps[] = $who; }
    $c['rep'] = array_slice($reps, 0, 20);
    if (count($c['rep']) >= $BLOCK_AT) { $c['blocked'] = true; }
    write_card($path, $c);
    out(200, array('ok' => true));
}

if (!editor_ok($c, $d['e'] ?? null)) { out(403, array('error' => 'editor')); }

if ($a === 'delete') {
    @unlink($path);
    out(200, array('ok' => true));
}

if ($a === 'update') {
    if (!valid_b64($d['ct'] ?? null, $MAX_CT)) { out(400, array('error' => 'card')); }
    $fh = @fopen($path, 'c+');
    if (!$fh) { out(503, array('error' => 'write')); }
    flock($fh, LOCK_EX);
    $cur = json_decode((string)stream_get_contents($fh), true);
    if (!is_array($cur)) { flock($fh, LOCK_UN); fclose($fh); out(404, array('error' => 'none')); }
    if ((int)($d['base'] ?? 0) !== (int)$cur['ver']) {   // someone else changed it first: the editor gets the newest and decides
        flock($fh, LOCK_UN); fclose($fh);
        out(409, array('error' => 'conflict', 'ver' => (int)$cur['ver'], 'ct' => $cur['ct'], 'upd' => (int)$cur['upd']));
    }
    $cur['ct'] = $d['ct']; $cur['ver'] = (int)$cur['ver'] + 1; $cur['upd'] = $now; $cur['exp'] = $now + $KEEP_DAYS * 86400;
    ftruncate($fh, 0); rewind($fh); fwrite($fh, json_encode($cur)); fflush($fh); flock($fh, LOCK_UN); fclose($fh);
    out(200, array('ok' => true, 'ver' => (int)$cur['ver'], 'upd' => $now));
}

out(400, array('error' => 'action'));
