<?php
// Receiver of the usage statistics (generated by sites/atomou/build.py from stats_receiver.php.tpl; do not edit the generated file by hand).
// Counts of fixed items only: no text, no dates, no ids, no address.  One JSON file per day in <site folder>/stats/ (outside the web root).
date_default_timezone_set('Asia/Tokyo');
header('X-Robots-Tag: noindex');
if (($_SERVER['REQUEST_METHOD'] ?? '') !== 'POST') { http_response_code(405); exit; }
$raw = file_get_contents('php://input', false, null, 0, 4097);
if ($raw === false || strlen($raw) > 4096) { http_response_code(413); exit; }
$d = json_decode($raw, true);
if (!is_array($d) || ($d['v'] ?? 0) !== 1 || !is_array($d['c'] ?? null)) { http_response_code(400); exit; }
$re = '__RE__';
$clean = array(); $n = 0;
foreach ($d['c'] as $k => $v) {
    if (++$n > 40) { break; }
    if (!is_string($k) || strlen($k) > 80 || !preg_match($re, $k)) { continue; }
    $v = (int)$v;
    if ($v < 1) { continue; }
    $clean[$k] = $v > 50 ? 50 : $v;
}
if (!$clean) { http_response_code(204); exit; }
$site = dirname(__DIR__, 2);                       // public_html/api/e.php -> <site folder>
$dir = $site . '/stats';
if (!is_dir($dir) && !@mkdir($dir, 0700, true)) { http_response_code(204); exit; }
// A limit on requests per sender and day: a salted daily hash of the address, kept only in a small counter file that is removed the next day.
$ip = (string)($_SERVER['REMOTE_ADDR'] ?? '');
$who = substr(hash('sha256', $ip . '|' . date('Y-m-d') . '|' . basename($site) . '|stats'), 0, 16);
$rate = $dir . '/rate-' . date('Ymd') . '-' . $who;
$r = is_file($rate) ? (int)file_get_contents($rate) : 0;
if ($r >= 300) { http_response_code(429); exit; }
@file_put_contents($rate, (string)($r + 1), LOCK_EX);
foreach ((glob($dir . '/rate-*') ?: array()) as $f) { if (strpos($f, '/rate-' . date('Ymd') . '-') === false) { @unlink($f); } }
$fh = @fopen($dir . '/' . date('Y-m-d') . '.json', 'c+');
if (!$fh) { http_response_code(204); exit; }
flock($fh, LOCK_EX);
$cur = json_decode((string)stream_get_contents($fh), true);
if (!is_array($cur)) { $cur = array(); }
foreach ($clean as $k => $v) {
    if (isset($cur[$k])) { $cur[$k] += $v; } elseif (count($cur) < 2000) { $cur[$k] = $v; }
}
ftruncate($fh, 0); rewind($fh); fwrite($fh, json_encode($cur)); fflush($fh); flock($fh, LOCK_UN); fclose($fh);
http_response_code(204);
