<?php
// Words that visitors ask us to look up (generated by sites/atomou/build.py from words_receiver.php.tpl; do not edit the generated file by hand).
// A visitor presses "このワードを調べてもらう" on a word; the page sends {"v":1,"w":"<the word>"}.  What is kept: the word, the time and a short random id, one JSON line per word in
// <site folder>/inbox/words-YYYYMM.jsonl (outside public_html).  NOT kept: the visitor's address (a salted daily hash is used only to count how many words one sender sends today, in a small
// file that is removed the next day), no cookie, no account.  The words are copied off the server ENCRYPTED by a workflow and read on the owner's PC (sites/atomou/words.py).
// A word that holds a forbidden term (gambling, adult, crime, a death) or looks like personal information (a phone number, an address, an e-mail, a URL) is refused.
date_default_timezone_set('Asia/Tokyo');
header('Content-Type: application/json; charset=utf-8');
header('Cache-Control: no-store');
header('X-Robots-Tag: noindex');
$SITE_URL = '__SITE_URL__';
$TERMS = __TERMS__;
$PERSONAL = __PERSONAL__;
$MIN = __MIN__;
$MAX = __MAX__;
$PER_DAY = __PER_DAY__;     // words per sender and day
$ALL_PER_DAY = 600;         // words per day, all senders
$KEEP_DAYS = 200;           // a month's file older than this is deleted

function out($code, $data) { http_response_code($code); echo json_encode($data, JSON_UNESCAPED_UNICODE); exit; }
if (($_SERVER['REQUEST_METHOD'] ?? '') !== 'POST') { out(405, array('error' => 'method')); }
$origin = (string)($_SERVER['HTTP_ORIGIN'] ?? '');
$oh = (string)parse_url($origin, PHP_URL_HOST); $sh = (string)parse_url($SITE_URL, PHP_URL_HOST);
if ($origin !== '' && $oh !== $sh && substr($oh, -(strlen($sh) + 1)) !== '.' . $sh) { out(403, array('error' => 'origin')); }   // the pages of this site (and its demo sub-domain) only
$raw = file_get_contents('php://input', false, null, 0, 1001);
if ($raw === false || strlen($raw) > 1000) { out(413, array('error' => 'size')); }
$d = json_decode($raw, true);
if (!is_array($d) || ($d['v'] ?? 0) !== 1 || !is_string($d['w'] ?? null)) { out(400, array('error' => 'request')); }
$w = trim(preg_replace('/[\x00-\x1f\x7f<>"\'&\\\\]/u', '', $d['w']));
$len = function_exists('mb_strlen') ? mb_strlen($w, 'UTF-8') : strlen($w);
if ($len < $MIN || $len > $MAX) { out(422, array('error' => 'length')); }
$flat = function_exists('mb_convert_kana') ? mb_convert_kana($w, 'KVa', 'UTF-8') : $w;     // full-width letters and digits to half-width, half-width katakana to full
$flat = function_exists('mb_strtolower') ? mb_strtolower($flat, 'UTF-8') : strtolower($flat);
foreach ($TERMS as $t) { if ($t !== '' && strpos($flat, $t) !== false) { out(422, array('error' => 'word')); } }
foreach ($PERSONAL as $p) { if (@preg_match('/' . $p . '/iu', $flat) === 1) { out(422, array('error' => 'word')); } }
$site = dirname(__DIR__, 2);                       // public_html/api/w.php -> <site folder>   (public_html/demo/api/w.php -> the same one)
$dir = $site . '/inbox';
if (!is_dir($dir) && !@mkdir($dir, 0700, true)) { out(503, array('error' => 'storage')); }
// the limits: a salted daily hash of the address (not an address, not kept after the day), and a count of the day
$ip = (string)($_SERVER['REMOTE_ADDR'] ?? '');
$who = substr(hash('sha256', $ip . '|' . date('Y-m-d') . '|' . basename($site) . '|words'), 0, 16);
$rate = $dir . '/wrate-' . date('Ymd') . '-' . $who;
$r = is_file($rate) ? (int)file_get_contents($rate) : 0;
if ($r >= $PER_DAY) { out(429, array('error' => 'rate')); }
$all = $dir . '/wall-' . date('Ymd');
$n = is_file($all) ? (int)file_get_contents($all) : 0;
if ($n >= $ALL_PER_DAY) { out(429, array('error' => 'full')); }
@file_put_contents($rate, (string)($r + 1), LOCK_EX);
@file_put_contents($all, (string)($n + 1), LOCK_EX);
foreach ((glob($dir . '/wrate-*') ?: array()) as $f) { if (strpos($f, '/wrate-' . date('Ymd') . '-') === false) { @unlink($f); } }
foreach ((glob($dir . '/wall-*') ?: array()) as $f) { if (substr($f, -8) !== date('Ymd')) { @unlink($f); } }
foreach ((glob($dir . '/words-*.jsonl') ?: array()) as $f) {
    if (preg_match('/words-(\d{4})(\d{2})\.jsonl$/', $f, $m) && mktime(0, 0, 0, (int)$m[2], 28, (int)$m[1]) < time() - $KEEP_DAYS * 86400) { @unlink($f); }
}
$line = json_encode(array('id' => bin2hex(random_bytes(4)), 'at' => date('c'), 'site' => 'atomou', 'kind' => 'word', 'message' => $w, 'email' => '', 'page' => ''), JSON_UNESCAPED_UNICODE) . "\n";
$file = $dir . '/words-' . date('Ym') . '.jsonl';
if (@file_put_contents($file, $line, FILE_APPEND | LOCK_EX) === false) { out(503, array('error' => 'storage')); }
@chmod($file, 0600);
out(200, array('ok' => true));
