"""The sites' own contact form: a plain HTML form, a small PHP receiver and a thank-you page (no Google Form, no e-mail address on the page).

    cfg["contact_own"] = true       switches a site to this form
    cfg["contact_kinds"] = [...]    the choices of the "kind" menu (the first one is the default)

The receiver (contact/send.php) appends each message as one JSON line to <site folder>/inbox/YYYY-MM.jsonl, which lies OUTSIDE the web root and
survives deploys (a deploy swaps only public_html).  Spam control without a third-party service: a hidden honeypot field, at most two links in a
message, at most five messages per sender and day (the sender is only a salted daily hash of the IP address, never the address itself).
The receiver also mails each message to info@<the site's domain> (built at run time from the site folder's name: no address is printed on a page or written in the repository).
A daily GitHub Actions job (.github/workflows/inbox.yml, sokuhou/inbox.py) copies new lines into the repository, where the routines read them.
"""
from __future__ import annotations

import json

from sokuhou.sitekit import esc

DEFAULT_KINDS = ["データの誤りのご指摘", "ご意見・ご要望", "その他"]
THANKS_PATH = "/contact/thanks.html"

STYLE = """<style>
.cf { display: grid; gap: 14px; max-width: 640px; margin: 18px 0; padding: 18px 20px; background: var(--card, #fff); border: var(--line2, 1px solid #b9c2bd); border-radius: var(--radius, 14px); }
.cf label { display: grid; gap: 4px; font-weight: 700; font-size: .92rem; }
.cf label small { font-weight: 400; color: var(--muted, #5d6a62); }
.cf input, .cf select, .cf textarea { width: 100%; box-sizing: border-box; padding: .6em .75em; border: var(--line2, 1px solid #9aa5a0); border-radius: 10px; background: var(--bg, #fff); color: inherit; font: inherit; }
.cf textarea { min-height: 9em; resize: vertical; }
.cf .cf-hp { position: absolute; left: -9999px; width: 1px; height: 1px; overflow: hidden; }
.cf button { justify-self: start; padding: .65em 1.6em; border: var(--line, 1px solid #333); border-radius: 999px; background: var(--brand, var(--pink, #17606b)); color: #fff; font: inherit; font-weight: 800; cursor: pointer; }
.cf .cf-note { margin: 0; font-size: .82rem; color: var(--muted, #5d6a62); }
</style>"""


def form_html(cfg: dict, *, default_kind: str = "", message_hint: str = "", page_hint: bool = True) -> str:
    kinds = cfg.get("contact_kinds") or DEFAULT_KINDS
    opts = "".join(f'<option value="{esc(k)}"{" selected" if k == (default_kind or kinds[0]) else ""}>{esc(k)}</option>' for k in kinds)
    page = ('<label>該当するページのアドレス(わかれば)<input type="text" name="page" maxlength="200" placeholder="例: https://…/gift/…/" autocomplete="off"></label>'
            if page_hint else "")
    return f"""{STYLE}
<form class="cf" action="/contact/send.php" method="post" accept-charset="UTF-8">
<label>お問い合わせの種類<select name="kind" required>{opts}</select></label>
<label>ご用件<small>5文字以上、2000文字以内。</small><textarea name="message" required minlength="5" maxlength="2000" placeholder="{esc(message_hint)}"></textarea></label>
{page}
<label>お返事がほしいときのメールアドレス<small>省略できます。いただいても、お返事できないことがあります。</small><input type="email" name="email" maxlength="200" autocomplete="email"></label>
<div class="cf-hp" aria-hidden="true"><label>この欄は空のままにしてください<input type="text" name="website" tabindex="-1" autocomplete="off"></label></div>
<button type="submit">送信する</button>
<p class="cf-note">送信すると、<a href="/privacy/">プライバシーポリシー</a>の内容に同意したものとみなします。いただいた内容は、サイトの改善と、お返事のためだけに使います。</p>
</form>"""


def thanks_body(cfg: dict) -> str:
    return ('<h1>送信しました</h1><p>お問い合わせを受け付けました。ありがとうございます。内容は、確認して、サイトの改善に役立てます。'
            'お返事は、できないことがあります。</p><p><a class="btn" href="/">トップページへ戻る</a></p>')


def _php_text(text: str) -> str:
    """Text that sits inside a PHP string in the template: no quote, backslash, dollar sign or line break can end or alter the string."""
    return "".join(c for c in str(text) if c >= " " and c not in "\"'\\${}")


def send_php(cfg: dict) -> str:
    kinds = json.dumps(cfg.get("contact_kinds") or DEFAULT_KINDS, ensure_ascii=False)
    return r"""<?php
// Receiver of the contact form (generated by sokuhou/contactform.py; do not edit by hand).
// Appends one JSON line per message to <site folder>/inbox/YYYY-MM.jsonl (outside the web root).
date_default_timezone_set('Asia/Tokyo');
header('Content-Type: text/html; charset=UTF-8');
header('X-Robots-Tag: noindex');
$KINDS = json_decode('__KINDS__', true);

function fail($code, $msg) {
    http_response_code($code);
    $s = 'font:16px/1.8 sans-serif;max-width:32em;margin:2.5em auto;padding:0 1em';
    echo '<!doctype html><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>送信できませんでした</title>'
       . '<p style="' . $s . '">' . htmlspecialchars($msg, ENT_QUOTES, 'UTF-8') . '</p>'
       . '<p style="' . $s . '"><a href="/contact/">お問い合わせに戻る</a></p>';
    exit;
}
function clip($s, $n) {
    return function_exists('mb_substr') ? mb_substr($s, 0, $n, 'UTF-8') : substr($s, 0, $n * 3);
}

if (($_SERVER['REQUEST_METHOD'] ?? '') !== 'POST') { fail(405, 'このページは、お問い合わせフォームから送信するためのものです。'); }
if (trim((string)($_POST['website'] ?? '')) !== '') { header('Location: __THANKS__', true, 303); exit; }   // honeypot: looks successful, stores nothing

$kind = (string)($_POST['kind'] ?? '');
if (!in_array($kind, $KINDS, true)) { fail(400, 'お問い合わせの種類を選んでください。'); }
$message = str_replace("\r\n", "\n", trim((string)($_POST['message'] ?? '')));
$len = preg_match_all('/./us', $message);
if ($len < 5) { fail(400, 'ご用件を、5文字以上で書いてください。'); }
if ($len > 2000) { fail(400, 'ご用件は、2000文字以内でお願いします。'); }
if (preg_match_all('~https?://~i', $message) > 2) { fail(400, 'リンクは、2つまでにしてください。'); }
$email = trim((string)($_POST['email'] ?? ''));
if ($email !== '' && (strlen($email) > 200 || !filter_var($email, FILTER_VALIDATE_EMAIL))) { fail(400, 'メールアドレスの形式を確認してください。'); }
$page = clip(trim((string)($_POST['page'] ?? '')), 200);

$site = dirname(__DIR__, 2);                       // public_html/contact/send.php -> <site folder>
$inbox = $site . '/inbox';
if (!is_dir($inbox) && !@mkdir($inbox, 0700, true)) { fail(500, '保存できませんでした。時間をおいて、もう一度お試しください。'); }

$ip = (string)($_SERVER['REMOTE_ADDR'] ?? '');
$who = substr(hash('sha256', $ip . '|' . date('Y-m-d') . '|' . basename($site)), 0, 16);   // a daily hash, never the address
$rate = $inbox . '/rate-' . date('Ymd') . '-' . $who;
$n = is_file($rate) ? (int)file_get_contents($rate) : 0;
if ($n >= 5) { fail(429, '本日の送信は、上限に達しました。明日、もう一度お試しください。'); }
@file_put_contents($rate, (string)($n + 1), LOCK_EX);
foreach ((glob($inbox . '/rate-*') ?: array()) as $f) { if (strpos($f, '/rate-' . date('Ymd') . '-') === false) { @unlink($f); } }

$rec = array('id' => bin2hex(random_bytes(6)), 'at' => date('c'), 'site' => basename($site), 'kind' => $kind, 'message' => $message,
             'email' => $email, 'page' => $page, 'who' => $who, 'ua' => clip((string)($_SERVER['HTTP_USER_AGENT'] ?? ''), 120));
$ok = @file_put_contents($inbox . '/' . date('Y-m') . '.jsonl', json_encode($rec, JSON_UNESCAPED_UNICODE) . "\n", FILE_APPEND | LOCK_EX);
if ($ok === false) { fail(500, '保存できませんでした。時間をおいて、もう一度お試しください。'); }

// Mail the message to the operator's address of this site: info@ + the domain (the site folder is named after the domain).  The address is built
// here at run time and is printed on no page and written in no file of the repository.  The line saved above is the record: a mail that fails
// (or an unexpected folder name) never fails the submission.
$domain = basename($site);
if (preg_match('/^[a-z0-9-]+(\.[a-z0-9-]+)+$/i', $domain)) {
    $to = 'info@' . $domain;
    $subject = '[__SITE__] お問い合わせ: ' . $kind;
    $body = "サイト: __SITE__ (" . $domain . ")\n種類: " . $kind . "\n日時: " . date('Y-m-d H:i:s') . "\nページ: " . $page
          . "\n返信先: " . ($email !== '' ? $email : '(なし)') . "\n\n" . $message . "\n";
    $h = array('From: ' . $to, 'MIME-Version: 1.0', 'Content-Type: text/plain; charset=UTF-8', 'Content-Transfer-Encoding: base64');
    if ($email !== '') { $h[] = 'Reply-To: ' . $email; }          // the address was validated above: no line breaks can be in it
    @mail($to, '=?UTF-8?B?' . base64_encode($subject) . '?=', chunk_split(base64_encode($body)), implode("\r\n", $h), '-f' . $to);
}
header('Location: __THANKS__', true, 303);
""".replace("__KINDS__", kinds.replace("\\", "\\\\").replace("'", "\\'")).replace("__THANKS__", THANKS_PATH).replace("__SITE__", _php_text(cfg["site_name"]))
